name = "Amna Pir Muhammad"
license = "Amna"
licenselink = ""
description = "Hi This is me, Phd student "
homepage = "https://github.com/amnapir/amnapir1"
demosite = ""
tags = ["resume",
        "portfolio",
        "personal",
        "blog",
        "projects",
        "mobile",
        "gallery",
        "search",
        "customizable",
        "technical",
        "product",
        "slide"
        ]
features = ["page builder", "widgets", "search", "research publication system", 
            "blog", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "Amna Pir Muhammad"
  homepage = "https://github.com/amnapir/amnapir1"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
